In [ ]:
# this notebook is for counting the inputs tokens for all the 4 granularities, 
# to have an estimate of the cost of the experiments.

# conclusion: too expensive to use the open-ai models (at least the good ones)

In [41]:
from tqdm.notebook import tqdm

from pathlib import Path
import pandas as pd


GRANURALITIES = ["file", "class", "method", "block"]
DATA_FOLDER_PATH = "./data/"

code_snippets = {}

# Iterates over the directory and prints only files
for granularity in GRANURALITIES:
    folder_path = f"{DATA_FOLDER_PATH}/{granularity}"
    path = Path(folder_path)
    projects_file_names = [f.name for f in path.iterdir() if f.is_file()]

    code_snippets[granularity] = {}
    for project_file_name in projects_file_names:
        project_name = project_file_name.split("-")[0]
        
        code_snippets[granularity][project_name] = pd.read_csv(f"{folder_path}/{project_file_name}")
    

PROJECTS_NAMES = list(code_snippets[GRANURALITIES[0]].keys())

In [42]:
example_df = code_snippets["file"][PROJECTS_NAMES[0]]

ALL_COMMENTS_COLUMNS = [col for col in example_df.columns if "comment" in col.lower() and "each" not in col.lower() and type(example_df[col][0]) == str]

# verify that all granularities have the same comment columns
for granularity in GRANURALITIES:
    example_df = code_snippets[granularity][PROJECTS_NAMES[0]]
    all_comments_columns = [col for col in example_df.columns if "comment" in col.lower() and "each" not in col.lower() and type(example_df[col][0]) == str]
    assert all_comments_columns == ALL_COMMENTS_COLUMNS, f"Granularity {granularity} has different comment columns: {all_comments_columns} != {ALL_COMMENTS_COLUMNS}"

In [43]:
def remove_comments(code : str, comments_set : str) -> str:
    for comment in comments_set:
        if comment.strip() != "":
            code = code.replace(comment, "")
    
    return code

In [44]:

for granularity in tqdm(GRANURALITIES, desc="granularity", position=0):
    for project_name in tqdm(PROJECTS_NAMES, desc="project", position=1, leave=False):
        df = code_snippets[granularity][project_name]
        df["code_without_comments"] = df.apply(lambda row: remove_comments(row["Content"], row[ALL_COMMENTS_COLUMNS]), axis=1)

granularity:   0%|          | 0/4 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

In [45]:
import tiktoken

MODEL_NAME = "gpt-5"  # Replace with your model name

# Automatically retrieves the correct encoding (e.g., o200k_base for gpt-4o)
encoding = tiktoken.encoding_for_model(MODEL_NAME)

def count_tokens(text: str) -> int:
    
    # Encode the text into integer token IDs
    token_list = encoding.encode(text)
    
    # The number of integers in the list is your token count
    return len(token_list)

text_to_check = "Counting tokens with tiktoken is incredibly fast! 🚀"

print(f"Token Count: {count_tokens(text_to_check)}")

Token Count: 12

In [46]:
count_tokens("yes"), count_tokens("no")

(1, 1)

In [47]:

code_column = "code_without_comments"


for granularity in tqdm(GRANURALITIES, desc="granularity", position=0):
    for project_name in tqdm(PROJECTS_NAMES, desc="project", position=1, leave=False):
        code_df = code_snippets[granularity][project_name]
        code_df["token_count"] = code_df[code_column].apply(count_tokens)
        # store back if you want to ensure the dict holds the updated df (usually not needed)
        code_snippets[granularity][project_name] = code_df

granularity:   0%|          | 0/4 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

project:   0%|          | 0/18 [00:00<?, ?it/s]

In [48]:
granularity = "file"
project_name = PROJECTS_NAMES[0]

code_df = code_snippets[granularity][project_name]

code_df.token_count.describe()

count     1498.00000
mean      2168.12283
std       4043.65019
min         12.00000
25%        418.25000
50%        919.50000
75%       2336.25000
max      91208.00000
Name: token_count, dtype: float64

In [ ]:
total_input_tokens = 0

for granularity in GRANURALITIES:
    for project_name in PROJECTS_NAMES:
        code_df = code_snippets[granularity][project_name]
        total_input_tokens += code_df.token_count.sum() + 60 * code_df.shape[0] # 200 is the number of tokens in the prompt without the code snippet, which is the same for all rows

total_output_tokens = 2 * sum([df.shape[0] for granularity in GRANURALITIES for project_name in PROJECTS_NAMES for df in [code_snippets[granularity][project_name]]])

print(f"Total input tokens across all granularities and projects: {total_input_tokens}") # 176131675
print(f"Total output tokens across all granularities and projects: {total_output_tokens}")

In [50]:
import json

with open("gpt_pricing.json", "r") as f:
    gpt_pricing = json.load(f)

In [51]:
model_price_df = pd.DataFrame(columns=['model', 'experiment cost (USD)'])

# all of our prompts will be less than 272.000 tokens
# so we can use short context pricing for all the LLM calls
context_size = "short_context"

for pricing_info in gpt_pricing:
    model = pricing_info["model"]

    prices = pricing_info[context_size]

    input_price_per_1M_tokens = float(prices["input"][1:])
    output_price_per_1M_tokens = float(prices["output"][1:])

    input_cost = (total_input_tokens / 1_000_000) * input_price_per_1M_tokens
    output_cost = (total_output_tokens / 1_000_000) * output_price_per_1M_tokens

    experiment_cost = input_cost + output_cost

    print(f"Model: {model}")
    # print(f"Total input price: {input_cost:.2f} USD")
    # print(f"Total output price: {output_cost:.2f} USD")
    print(f"Total experiment cost: \033[1m{experiment_cost:.2f} USD\033[0m")
    print("-" * 30)


    model_price_df.loc[len(model_price_df)] = [model, f"$ {round(experiment_cost, 2)}"]

print('#' * 30 + 'Other models pricing: ')


with open("other_models_pricing.json", "r") as f:
    other_pricing = json.load(f)

for pricing_info in other_pricing:
    model = pricing_info["Model"]

    prices = pricing_info

    input_price_per_1M_tokens = prices["Input"]
    output_price_per_1M_tokens = prices["Output"]

    input_cost = (total_input_tokens / 1_000_000) * input_price_per_1M_tokens
    output_cost = (total_output_tokens / 1_000_000) * output_price_per_1M_tokens

    experiment_cost = input_cost + output_cost

    print(f"Model: {model}")
    # print(f"Total input price: {input_cost:.2f} USD")
    # print(f"Total output price: {output_cost:.2f} USD")
    print(f"Total experiment cost: \033[1m{experiment_cost:.2f} USD\033[0m")
    print("-" * 30)

    model_price_df.loc[len(model_price_df)] = [model, f"$ {round(experiment_cost, 2)}"]

Model: gpt-5.5
Total experiment cost: 1012.03 USD
------------------------------
Model: gpt-5.5-pro
Total experiment cost: 6072.20 USD
------------------------------
Model: gpt-5.4
Total experiment cost: 506.02 USD
------------------------------
Model: gpt-5.4-mini
Total experiment cost: 151.81 USD
------------------------------
Model: gpt-5.4-nano
Total experiment cost: 40.52 USD
------------------------------
Model: gpt-5.4-pro
Total experiment cost: 6072.20 USD
------------------------------
##############################Other models pricing:
Model: gpt-5.2
Total experiment cost: 356.77 USD
------------------------------
Model: gpt-5.2-pro
Total experiment cost: 4281.20 USD
------------------------------
Model: gpt-5.1
Total experiment cost: 254.83 USD
------------------------------
Model: gpt-5
Total experiment cost: 254.83 USD
------------------------------
Model: gpt-5-mini
Total experiment cost: 50.97 USD
------------------------------
Model: gpt-5-nano
Total experiment cost: 10.19 USD
------------------------------
Model: gpt-5-pro
Total experiment cost: 3058.00 USD
------------------------------
Model: gpt-4.1
Total experiment cost: 401.89 USD
------------------------------
Model: gpt-4.1-mini
Total experiment cost: 80.38 USD
------------------------------
Model: gpt-4.1-nano
Total experiment cost: 20.09 USD
------------------------------
Model: gpt-4o
Total experiment cost: 502.37 USD
------------------------------
Model: gpt-4o-mini
Total experiment cost: 30.14 USD
------------------------------
Model: o4-mini
Total experiment cost: 221.04 USD
------------------------------
Model: o3
Total experiment cost: 401.89 USD
------------------------------
Model: o3-mini
Total experiment cost: 221.04 USD
------------------------------
Model: o3-pro
Total experiment cost: 4018.94 USD
------------------------------
Model: o1
Total experiment cost: 3014.21 USD
------------------------------
Model: o1-mini
Total experiment cost: 221.04 USD
------------------------------
Model: o1-pro
Total experiment cost: 30142.06 USD
------------------------------
Model: gpt-4o-2024-05-13
Total experiment cost: 1001.09 USD
------------------------------
Model: gpt-4-turbo-2024-04-09
Total experiment cost: 2002.17 USD
------------------------------
Model: gpt-4-0125-preview
Total experiment cost: 2002.17 USD
------------------------------
Model: gpt-4-1106-preview
Total experiment cost: 2002.17 USD
------------------------------
Model: gpt-4-1106-vision-preview
Total experiment cost: 2002.17 USD
------------------------------
Model: gpt-4-0613
Total experiment cost: 5984.62 USD
------------------------------
Model: gpt-4-0314
Total experiment cost: 5984.62 USD
------------------------------
Model: gpt-4-32k
Total experiment cost: 11969.24 USD
------------------------------
Model: gpt-3.5-turbo
Total experiment cost: 100.11 USD
------------------------------
Model: gpt-3.5-turbo-0125
Total experiment cost: 100.11 USD
------------------------------
Model: gpt-3.5-turbo-1106
Total experiment cost: 199.49 USD
------------------------------
Model: gpt-3.5-turbo-0613
Total experiment cost: 298.50 USD
------------------------------
Model: gpt-3.5-0301
Total experiment cost: 298.50 USD
------------------------------
Model: gpt-3.5-turbo-instruct
Total experiment cost: 298.50 USD
------------------------------
Model: gpt-3.5-turbo-16k-0613
Total experiment cost: 597.00 USD
------------------------------
Model: davinci-002
Total experiment cost: 397.51 USD
------------------------------
Model: babbage-002
Total experiment cost: 79.50 USD
------------------------------

In [52]:
model_price_df.to_csv("model_price_estimation.csv", index=False)

In [53]:
model_price_df

                        model experiment cost (USD)
0                     gpt-5.5             $ 1012.03
1                 gpt-5.5-pro              $ 6072.2
2                     gpt-5.4              $ 506.02
3                gpt-5.4-mini              $ 151.81
4                gpt-5.4-nano               $ 40.52
5                 gpt-5.4-pro              $ 6072.2
6                     gpt-5.2              $ 356.77
7                 gpt-5.2-pro              $ 4281.2
8                     gpt-5.1              $ 254.83
9                       gpt-5              $ 254.83
10                 gpt-5-mini               $ 50.97
11                 gpt-5-nano               $ 10.19
12                  gpt-5-pro              $ 3058.0
13                    gpt-4.1              $ 401.89
14               gpt-4.1-mini               $ 80.38
15               gpt-4.1-nano               $ 20.09
16                     gpt-4o              $ 502.37
17                gpt-4o-mini               $ 30.14
18                    o4-mini              $ 221.04
19                         o3              $ 401.89
20                    o3-mini              $ 221.04
21                     o3-pro             $ 4018.94
22                         o1             $ 3014.21
23                    o1-mini              $ 221.04
24                     o1-pro            $ 30142.06
25          gpt-4o-2024-05-13             $ 1001.09
26     gpt-4-turbo-2024-04-09             $ 2002.17
27         gpt-4-0125-preview             $ 2002.17
28         gpt-4-1106-preview             $ 2002.17
29  gpt-4-1106-vision-preview             $ 2002.17
30                 gpt-4-0613             $ 5984.62
31                 gpt-4-0314             $ 5984.62
32                  gpt-4-32k            $ 11969.24
33              gpt-3.5-turbo              $ 100.11
34         gpt-3.5-turbo-0125              $ 100.11
35         gpt-3.5-turbo-1106              $ 199.49
36         gpt-3.5-turbo-0613               $ 298.5
37               gpt-3.5-0301               $ 298.5
38     gpt-3.5-turbo-instruct               $ 298.5
39     gpt-3.5-turbo-16k-0613               $ 597.0
40                davinci-002              $ 397.51
41                babbage-002                $ 79.5

In [54]:
round(3.14159, 2)

3.14

In [55]:
model_price_df

                        model experiment cost (USD)
0                     gpt-5.5             $ 1012.03
1                 gpt-5.5-pro              $ 6072.2
2                     gpt-5.4              $ 506.02
3                gpt-5.4-mini              $ 151.81
4                gpt-5.4-nano               $ 40.52
5                 gpt-5.4-pro              $ 6072.2
6                     gpt-5.2              $ 356.77
7                 gpt-5.2-pro              $ 4281.2
8                     gpt-5.1              $ 254.83
9                       gpt-5              $ 254.83
10                 gpt-5-mini               $ 50.97
11                 gpt-5-nano               $ 10.19
12                  gpt-5-pro              $ 3058.0
13                    gpt-4.1              $ 401.89
14               gpt-4.1-mini               $ 80.38
15               gpt-4.1-nano               $ 20.09
16                     gpt-4o              $ 502.37
17                gpt-4o-mini               $ 30.14
18                    o4-mini              $ 221.04
19                         o3              $ 401.89
20                    o3-mini              $ 221.04
21                     o3-pro             $ 4018.94
22                         o1             $ 3014.21
23                    o1-mini              $ 221.04
24                     o1-pro            $ 30142.06
25          gpt-4o-2024-05-13             $ 1001.09
26     gpt-4-turbo-2024-04-09             $ 2002.17
27         gpt-4-0125-preview             $ 2002.17
28         gpt-4-1106-preview             $ 2002.17
29  gpt-4-1106-vision-preview             $ 2002.17
30                 gpt-4-0613             $ 5984.62
31                 gpt-4-0314             $ 5984.62
32                  gpt-4-32k            $ 11969.24
33              gpt-3.5-turbo              $ 100.11
34         gpt-3.5-turbo-0125              $ 100.11
35         gpt-3.5-turbo-1106              $ 199.49
36         gpt-3.5-turbo-0613               $ 298.5
37               gpt-3.5-0301               $ 298.5
38     gpt-3.5-turbo-instruct               $ 298.5
39     gpt-3.5-turbo-16k-0613               $ 597.0
40                davinci-002              $ 397.51
41                babbage-002                $ 79.5

In [56]:
prompt = """
Act as an Technical Debt detector specialist. Tell if the following code has Technical Debt or not.
Only answer "yes" or "no".

Code: {"""

In [57]:
count_tokens(prompt)

32